version: "3.7"

services:
  grafana1:
    image: grafana/grafana:7.0.0
    ports:
      - "3000:3000"

  influxdb1:
    image: influxdb:1.7
    volumes:
      - ./influxdb:/var/lib/influxdb

  snmpd1:
    image: polinux/snmpd:alpine

  telegraf1:
    image: telegraf:1.14-alpine
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb1
      - snmpd1

